// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'show defaultTargetPlatform, kIsWeb, TargetPlatform;

//   await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdm_O5PTnI7vqasMQJeP5A-HP9hNy7als',
    appId: '1:971314115794:web:949358231b6917708ce90b',
    messagingSenderId: '971314115794',
    projectId: 'logbook-fav',
    authDomain: 'logbook-fav.firebaseapp.com',
    storageBucket: 'logbook-fav.firebasestorage.app',
    measurementId: 'G-Y1DS7PEGD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkj6T4pCoFmP4cETjScJUVUMfQKBTfNqk',
    appId: '1:971314115794:android:b42025cb663dcd188ce90b',
    messagingSenderId: '971314115794',
    projectId: 'logbook-fav',
    storageBucket: 'logbook-fav.firebasestorage.app',
  );
}
